### ISSUE TITLE
Consider replacing react-select with react-widget#*select

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/design-system#248]
As a aggregator of upstream ui libs, we have to provide consistently themed/styled/configured widgets. This task is easier if we have few deps and/or resurface other "aggregates" (as opposed to uni-taskers like react-select or react-dates). We should be shielding consumers from having to do the theming (whehter it be css-in-js or css pre-processor or whatever... this should be opaque to them)

Lets use this thread to:

* [ ] identify the LoE re migration react-select -> react-widgets
* [ ] what risks?
* [ ] voice general concerns

_Go!_

**Comment by eckdanny-osi** [comment]
one concern re "unitaskers" vs "aggregators" (or maybe this is an orthogonal concern): unitaskers tend to be more responsive w.r.t. repo maint. (e.g.; general pulse, merging of PRs, updating deps as they are realased, ...). This makes inuititive sense b/c the surface area is smaller. One concern moving to an aggregator is that the wait for upstream PRs or bugfixes (submitted by us or otherwise) may be longer. (atm looking at the react-widgets pulse, specifically the number of merged PRs in the last 5 mo's. Also the "Multiselect open/close on removing an item" issue that will be relevant to us immediately that was closed w/ no rationale)

**Comment by vikas199** [comment]
Mostly digital services are using libraries like react-select for multiselect and react-widgets for time widgets. But react widget is also providing a multi select which almost provides same functionality as react-select. Though there are some differences in the functionality of these libraries. 

The react-select multiselect has a good accessibility feature on enter and escape keys whereas in react-widgets multiselect we need to manually enforce this accessibility features on various keys. We can implement all accessibility features in react-widget multiselect manually but it would require some effort in doing that. 

Apart from accessibility the opening and closing of the drop down is quite favorable in react-select and gives a good user experience. In order to work with react-select we need to manually enforce the state in order to achieve this opening and closing of the drop down. 

One of the feature that react-select got is when you clear the values from the multiselect box the drop down is being closed during the clearing of the values but it is not same with react-widget multiselect. Again enforcing such kind of functionality would be risky. Implementing such kind of functionality would require good effort. There is already issue being raised on this behavior but has closed without any comments on it(https://github.com/jquense/react-widgets/issues/614)

The styling of the multiselect in both of these libraries is quite different. Again it is a call of the design and product team on how they want their multiselect field to look like.

what risks

There wouldn’t be a much heavy lift change for digital services from migrating to react widget’s multi-select. There is some difference in the props that are being passed onto the react-widgets multi-select.


It would be great for the dev’s to provide their opinions and comments whether they are Ok to migrate from react-select to react-widget’s multiselect.
