### ISSUE TITLE
White bar displaying on landing pages

### ISSUE THREAD

**Issue by c-dunwoodie** [ca-cwds/design-system#73]
White bar appears between the LHS nav and main area of page on both the Principles and Layouts landing pages.

Confirmed issue on: 
- Chrome Version 68.0.3440.106 (Official Build) (64-bit) 
- Safari Version 11.1 (13605.1.33.1.4)

**Comment by eckdanny-osi** [comment]
can someone confirm this? issue is 25 days old atm

**Comment by vikas199** [comment]
@eckdanny-osi. I'm checking this issue in chrome Version 70.0.3538.54 (Official Build) beta (64-bit). The issue does not seem to be reproduced. I'm attaching screenshots for chrome and safari browsers so that we can close the issue
![screen shot 2018-10-30 at 11 29 53 am](https://user-images.githubusercontent.com/28766943/47741346-4e505680-dc37-11e8-9ec6-a4a3eff6143e.png)
In safari

![screen shot 2018-10-30 at 11 32 24 am](https://user-images.githubusercontent.com/28766943/47741454-8e173e00-dc37-11e8-825c-5339ba0688d0.png)
